### ISSUE TITLE
Logstash not starting due to error

### ISSUE THREAD

**Issue by skluthe** [3ilson/pfelk#77]
Followed your ansible install and everything is working except for logstash. I'm getting this error:
```
ERROR] 2020-03-13 20:55:28.125 [[main]-pipeline-manager] javapipeline - Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<RuntimeError: Grok pattern file does not exist: /etc/logstash/conf.d/patterns/pf-12.2019.grok>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:445:in `block in add_patterns_from_files'", "org/jruby/RubyArray.java:1814:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:443:in `add_patterns_from_files'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:282:in `block in register'", "org/jruby/RubyArray.java:1814:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:278:in `block in register'", "org/jruby/RubyHash.java:1428:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:273:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:56:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:200:in `block in register_plugins'", "org/jruby/RubyArray.java:1814:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:199:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:502:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:212:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:154:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:109:in `block in start'"], "pipeline.sources"=>["/etc/logstash/conf.d/01-inputs.conf", "/etc/logstash/conf.d/11-firewall.conf", "/etc/logstash/conf.d/12-suricata.conf", "/etc/logstash/conf.d/13-snort.conf", "/etc/logstash/conf.d/15-others.conf", "/etc/logstash/conf.d/20-geoip.conf", "/etc/logstash/conf.d/50-outputs.conf"], :thread=>"#<Thread:0x4ec02327 run>"}
[ERROR] 2020-03-13 20:55:28.146 [Converge PipelineAction::Create<main>] agent - Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
```

**Comment by revere521** [comment]
It looks like the grok pattern file is missing as per "Grok pattern file does not exist: /etc/logstash/conf.d/patterns/pf-12.2019.grok"  in the error. 

I can't speak to what might have gone wrong - but do this to fix it:

```
sudo mkdir /etc/logstash/conf.d/patterns
cd /etc/logstash/conf.d/patterns/
sudo wget https://raw.githubusercontent.com/a3ilson/pfelk/master/conf.d/patterns/pf-12.2019.grok
```

**Comment by skluthe** [comment]
So the file was already there. Running logstash as root fixes this issue but I'd rather not. Permissions are correct on the file (opened them to 777 just in case but no luck)

**Comment by skluthe** [comment]
Also, now that it's working running as root none of the imported dashboards are working (not sure how to troubleshoot but will happily do it if given instructions)

**Comment by revere521** [comment]
does running elasticsearch, logstash and kibana as services fix the issue?

**Comment by skluthe** [comment]
No. I was running logstash as a service initially and no logs were getting passed. It does however work when running `sudo /usr/share/logstash/bin/logstash`
